version: "3.8"

services:
  hogwartsbackend:
    container_name: hogwartsbackend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "5076:5076"
    depends_on:
      - db
    networks:
      - aspnetcoreapp-network
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hogwarts
    networks:
      - aspnetcoreapp-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    container_name: hogwartsfrontend
    build:
      context: frontend/hogwarts-potions-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - hogwartsbackend 
    networks:
      - aspnetcoreapp-network  

volumes:
  pgdata: {}

networks:
  aspnetcoreapp-network:
    driver: bridge
