version: "3.8"

services:
  hogwartsbackend:
    container_name: hogwartsbackend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5076:5076"
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Port=5432;Database=hogwarts;User Id=postgres;Password=abcd1234!"
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abcd1234!
      - POSTGRES_DB=hogwarts
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}


